# Generated by Django 5.0.6 on 2024-07-05 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0001_initial'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='TestModel',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('name', models.CharField(max_length=100)),
        #     ],
        # ),
        # migrations.DeleteModel(
        #     name='User',
        # ),
    ]
