# Generated by Django 5.0.6 on 2024-07-05 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0004_article_articletag_category_comment_role_tag_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
