# Generated by Django 5.0.6 on 2024-07-09 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0005_delete_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='categoryID',
        ),
        migrations.AddField(
            model_name='article',
            name='categories',
            field=models.ManyToManyField(related_name='articles', to='NewsApp.category'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(through='NewsApp.ArticleTag', to='NewsApp.tag'),
        ),
    ]
