# Generated by Django 5.0.6 on 2024-07-12 10:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0008_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='publishTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
