# Generated by Django 5.0.6 on 2024-07-13 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0009_article_publishtime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='publishTime',
            new_name='publishDateTime',
        ),
        migrations.RemoveField(
            model_name='article',
            name='publishDate',
        ),
    ]
